# Use an existing Apache image as the base image
FROM httpd:2.4

# Copy the HTML and CSS files to the default Apache document root
COPY . /usr/local/apache2/htdocs/

# Expose port 80 for incoming traffic
EXPOSE 80
